[package]
name = "actix_web_api"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.1", features = ["sqlite", "r2d2"] }
dotenvy = "0.15"
